# Generated by Django 4.2.2 on 2023-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='option2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='option3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='option4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
